// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfZQgW4JBtKtJm0wrAdlNJXbpcKFTG9FM',
    appId: '1:703006298560:web:fb01655f5ad8b0ba5db825',
    messagingSenderId: '703006298560',
    projectId: 'abautoxproject',
    authDomain: 'abautoxproject.firebaseapp.com',
    storageBucket: 'abautoxproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_aUqSatJIIef4EGdFiPyyFLO6l8ocADY',
    appId: '1:703006298560:android:2e58839783b555985db825',
    messagingSenderId: '703006298560',
    projectId: 'abautoxproject',
    storageBucket: 'abautoxproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtrfv97wzb6u74h-d-aiqkd44tbLaJOXc',
    appId: '1:703006298560:ios:bc4a83f85431af025db825',
    messagingSenderId: '703006298560',
    projectId: 'abautoxproject',
    storageBucket: 'abautoxproject.firebasestorage.app',
    iosBundleId: 'com.abautoxapp.mobileios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtrfv97wzb6u74h-d-aiqkd44tbLaJOXc',
    appId: '1:703006298560:ios:bc4a83f85431af025db825',
    messagingSenderId: '703006298560',
    projectId: 'abautoxproject',
    storageBucket: 'abautoxproject.firebasestorage.app',
    iosBundleId: 'com.abautoxapp.mobileios',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfZQgW4JBtKtJm0wrAdlNJXbpcKFTG9FM',
    appId: '1:703006298560:web:ed60d57bd79c08885db825',
    messagingSenderId: '703006298560',
    projectId: 'abautoxproject',
    authDomain: 'abautoxproject.firebaseapp.com',
    storageBucket: 'abautoxproject.firebasestorage.app',
  );

}