// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'banners/data/models/banner_converter.dart';
import 'brands/data/models/brand_converter.dart';
import 'categories/data/models/category_converter.dart';
import 'chatbot/data/models/chat_message_converter.dart';
import 'notifications/data/models/notification_model.dart';
import 'products/data/models/media_converter.dart';
import 'products/data/models/product_converter.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 4315604926341530559),
    name: 'BrandObjectBox',
    lastPropertyId: const obx_int.IdUid(4, 5739220338375738239),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5914493387267848969),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6936088111536905682),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3953644210949368383),
        name: 'url',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5739220338375738239),
        name: 'externalId',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7295223596312789780),
    name: 'CategoryObjectBox',
    lastPropertyId: const obx_int.IdUid(6, 901545409389989015),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3193994855571102972),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2912409044124922330),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4933543142295380548),
        name: 'url',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 58665840423098682),
        name: 'items',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 592175416742668986),
        name: 'externalId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 901545409389989015),
        name: 'brands',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 142149026873509823),
    name: 'MediaObjectBox',
    lastPropertyId: const obx_int.IdUid(4, 7068482495701247043),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 766021378939991403),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 68292364190805987),
        name: 'url',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 350751851184631501),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7068482495701247043),
        name: 'productId',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 4586567559854766612),
    name: 'ProductObjectBox',
    lastPropertyId: const obx_int.IdUid(16, 5350406856469267773),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4479920085240397469),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 317713459971157570),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5798335708260810985),
        name: 'slug',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2112387888817980722),
        name: 'warranty',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 28986463738867514),
        name: 'state',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3195196929306529032),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2768764730937971954),
        name: 'price',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 46640368813470857),
        name: 'discount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2807675872431407267),
        name: 'featuresJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2276428863608359219),
        name: 'medias',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 8255731902632710813),
        name: 'categoryId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 4446655472623764377),
        name: 'brandId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 2107725386170610249),
        name: 'externalId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 6759303811350674742),
        name: 'category',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 2867329838053045093),
        name: 'brand',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 5350406856469267773),
        name: 'cta',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 7923811105843308182),
    name: 'BannerObjectBox',
    lastPropertyId: const obx_int.IdUid(6, 8362625925132158809),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3501805215244096966),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3526174087344131041),
        name: 'externalId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6750903517618356504),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6168077683088532582),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2185322192887914029),
        name: 'image',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8362625925132158809),
        name: 'link',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 7055027686109035790),
    name: 'ChatObjectBox',
    lastPropertyId: const obx_int.IdUid(5, 5279674479989527265),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6510647186065301376),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2456942448497961543),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2842697644565209481),
        name: 'isUser',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5718482840458487548),
        name: 'timestamp',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5279674479989527265),
        name: 'externalId',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 2183842583382835785),
    name: 'NotificationObjectBox',
    lastPropertyId: const obx_int.IdUid(7, 1526500761333533194),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3660932265052852859),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8931288054870090),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7430638736977842597),
        name: 'body',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6157552373074252062),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3542033952437634230),
        name: 'data',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5085156783930320423),
        name: 'receivedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1526500761333533194),
        name: 'isRead',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(7, 2183842583382835785),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    BrandObjectBox: obx_int.EntityDefinition<BrandObjectBox>(
      model: _entities[0],
      toOneRelations: (BrandObjectBox object) => [],
      toManyRelations: (BrandObjectBox object) => {},
      getId: (BrandObjectBox object) => object.id,
      setId: (BrandObjectBox object, int id) {
        object.id = id;
      },
      objectToFB: (BrandObjectBox object, fb.Builder fbb) {
        final nameOffset = object.name == null
            ? null
            : fbb.writeString(object.name!);
        final urlOffset = object.url == null
            ? null
            : fbb.writeString(object.url!);
        final externalIdOffset = object.externalId == null
            ? null
            : fbb.writeString(object.externalId!);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, urlOffset);
        fbb.addOffset(3, externalIdOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final externalIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final urlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final object = BrandObjectBox(
          id: idParam,
          externalId: externalIdParam,
          name: nameParam,
          url: urlParam,
        );

        return object;
      },
    ),
    CategoryObjectBox: obx_int.EntityDefinition<CategoryObjectBox>(
      model: _entities[1],
      toOneRelations: (CategoryObjectBox object) => [],
      toManyRelations: (CategoryObjectBox object) => {},
      getId: (CategoryObjectBox object) => object.id,
      setId: (CategoryObjectBox object, int id) {
        object.id = id;
      },
      objectToFB: (CategoryObjectBox object, fb.Builder fbb) {
        final nameOffset = object.name == null
            ? null
            : fbb.writeString(object.name!);
        final urlOffset = object.url == null
            ? null
            : fbb.writeString(object.url!);
        final externalIdOffset = object.externalId == null
            ? null
            : fbb.writeString(object.externalId!);
        final brandsOffset = object.brands == null
            ? null
            : fbb.writeString(object.brands!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, urlOffset);
        fbb.addInt64(3, object.items);
        fbb.addOffset(4, externalIdOffset);
        fbb.addOffset(5, brandsOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final externalIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final urlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final brandsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final itemsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final object = CategoryObjectBox(
          id: idParam,
          externalId: externalIdParam,
          name: nameParam,
          url: urlParam,
          brands: brandsParam,
          items: itemsParam,
        );

        return object;
      },
    ),
    MediaObjectBox: obx_int.EntityDefinition<MediaObjectBox>(
      model: _entities[2],
      toOneRelations: (MediaObjectBox object) => [],
      toManyRelations: (MediaObjectBox object) => {},
      getId: (MediaObjectBox object) => object.id,
      setId: (MediaObjectBox object, int id) {
        object.id = id;
      },
      objectToFB: (MediaObjectBox object, fb.Builder fbb) {
        final urlOffset = object.url == null
            ? null
            : fbb.writeString(object.url!);
        final typeOffset = object.type == null
            ? null
            : fbb.writeString(object.type!);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, urlOffset);
        fbb.addOffset(2, typeOffset);
        fbb.addInt64(3, object.productId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final urlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final productIdParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final object = MediaObjectBox(
          id: idParam,
          url: urlParam,
          type: typeParam,
          productId: productIdParam,
        );

        return object;
      },
    ),
    ProductObjectBox: obx_int.EntityDefinition<ProductObjectBox>(
      model: _entities[3],
      toOneRelations: (ProductObjectBox object) => [],
      toManyRelations: (ProductObjectBox object) => {},
      getId: (ProductObjectBox object) => object.id,
      setId: (ProductObjectBox object, int id) {
        object.id = id;
      },
      objectToFB: (ProductObjectBox object, fb.Builder fbb) {
        final nameOffset = object.name == null
            ? null
            : fbb.writeString(object.name!);
        final slugOffset = object.slug == null
            ? null
            : fbb.writeString(object.slug!);
        final warrantyOffset = object.warranty == null
            ? null
            : fbb.writeString(object.warranty!);
        final stateOffset = object.state == null
            ? null
            : fbb.writeString(object.state!);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final featuresJsonOffset = object.featuresJson == null
            ? null
            : fbb.writeString(object.featuresJson!);
        final mediasOffset = object.medias == null
            ? null
            : fbb.writeString(object.medias!);
        final categoryIdOffset = object.categoryId == null
            ? null
            : fbb.writeString(object.categoryId!);
        final brandIdOffset = object.brandId == null
            ? null
            : fbb.writeString(object.brandId!);
        final categoryOffset = object.category == null
            ? null
            : fbb.writeString(object.category!);
        final brandOffset = object.brand == null
            ? null
            : fbb.writeString(object.brand!);
        final ctaOffset = object.cta == null
            ? null
            : fbb.writeString(object.cta!);
        fbb.startTable(17);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, slugOffset);
        fbb.addOffset(3, warrantyOffset);
        fbb.addOffset(4, stateOffset);
        fbb.addOffset(5, descriptionOffset);
        fbb.addFloat64(6, object.price);
        fbb.addFloat64(7, object.discount);
        fbb.addOffset(8, featuresJsonOffset);
        fbb.addOffset(9, mediasOffset);
        fbb.addOffset(10, categoryIdOffset);
        fbb.addOffset(11, brandIdOffset);
        fbb.addInt64(12, object.externalId);
        fbb.addOffset(13, categoryOffset);
        fbb.addOffset(14, brandOffset);
        fbb.addOffset(15, ctaOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final externalIdParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          28,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final slugParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final ctaParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final warrantyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final stateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final priceParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final discountParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final featuresJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final mediasParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final brandParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final categoryIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final brandIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final object = ProductObjectBox(
          id: idParam,
          externalId: externalIdParam,
          name: nameParam,
          slug: slugParam,
          cta: ctaParam,
          warranty: warrantyParam,
          state: stateParam,
          description: descriptionParam,
          price: priceParam,
          discount: discountParam,
          featuresJson: featuresJsonParam,
          medias: mediasParam,
          category: categoryParam,
          brand: brandParam,
          categoryId: categoryIdParam,
          brandId: brandIdParam,
        );

        return object;
      },
    ),
    BannerObjectBox: obx_int.EntityDefinition<BannerObjectBox>(
      model: _entities[4],
      toOneRelations: (BannerObjectBox object) => [],
      toManyRelations: (BannerObjectBox object) => {},
      getId: (BannerObjectBox object) => object.id,
      setId: (BannerObjectBox object, int id) {
        object.id = id;
      },
      objectToFB: (BannerObjectBox object, fb.Builder fbb) {
        final titleOffset = object.title == null
            ? null
            : fbb.writeString(object.title!);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final imageOffset = object.image == null
            ? null
            : fbb.writeString(object.image!);
        final linkOffset = object.link == null
            ? null
            : fbb.writeString(object.link!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.externalId);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addOffset(4, imageOffset);
        fbb.addOffset(5, linkOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final externalIdParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          6,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final imageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final linkParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final object = BannerObjectBox(
          id: idParam,
          externalId: externalIdParam,
          title: titleParam,
          description: descriptionParam,
          image: imageParam,
          link: linkParam,
        );

        return object;
      },
    ),
    ChatObjectBox: obx_int.EntityDefinition<ChatObjectBox>(
      model: _entities[5],
      toOneRelations: (ChatObjectBox object) => [],
      toManyRelations: (ChatObjectBox object) => {},
      getId: (ChatObjectBox object) => object.id,
      setId: (ChatObjectBox object, int id) {
        object.id = id;
      },
      objectToFB: (ChatObjectBox object, fb.Builder fbb) {
        final textOffset = object.text == null
            ? null
            : fbb.writeString(object.text!);
        final timestampOffset = object.timestamp == null
            ? null
            : fbb.writeString(object.timestamp!);
        final externalIdOffset = object.externalId == null
            ? null
            : fbb.writeString(object.externalId!);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, textOffset);
        fbb.addBool(2, object.isUser);
        fbb.addOffset(3, timestampOffset);
        fbb.addOffset(4, externalIdOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final isUserParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          8,
        );
        final timestampParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final externalIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final object = ChatObjectBox(
          id: idParam,
          text: textParam,
          isUser: isUserParam,
          timestamp: timestampParam,
          externalId: externalIdParam,
        );

        return object;
      },
    ),
    NotificationObjectBox: obx_int.EntityDefinition<NotificationObjectBox>(
      model: _entities[6],
      toOneRelations: (NotificationObjectBox object) => [],
      toManyRelations: (NotificationObjectBox object) => {},
      getId: (NotificationObjectBox object) => object.id,
      setId: (NotificationObjectBox object, int id) {
        object.id = id;
      },
      objectToFB: (NotificationObjectBox object, fb.Builder fbb) {
        final titleOffset = object.title == null
            ? null
            : fbb.writeString(object.title!);
        final bodyOffset = object.body == null
            ? null
            : fbb.writeString(object.body!);
        final typeOffset = object.type == null
            ? null
            : fbb.writeString(object.type!);
        final dataOffset = object.data == null
            ? null
            : fbb.writeString(object.data!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, bodyOffset);
        fbb.addOffset(3, typeOffset);
        fbb.addOffset(4, dataOffset);
        fbb.addInt64(5, object.receivedAt?.millisecondsSinceEpoch);
        fbb.addBool(6, object.isRead);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final receivedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final bodyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final dataParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final receivedAtParam = receivedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(receivedAtValue);
        final isReadParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final object = NotificationObjectBox(
          id: idParam,
          title: titleParam,
          body: bodyParam,
          type: typeParam,
          data: dataParam,
          receivedAt: receivedAtParam,
          isRead: isReadParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [BrandObjectBox] entity fields to define ObjectBox queries.
class BrandObjectBox_ {
  /// See [BrandObjectBox.id].
  static final id = obx.QueryIntegerProperty<BrandObjectBox>(
    _entities[0].properties[0],
  );

  /// See [BrandObjectBox.name].
  static final name = obx.QueryStringProperty<BrandObjectBox>(
    _entities[0].properties[1],
  );

  /// See [BrandObjectBox.url].
  static final url = obx.QueryStringProperty<BrandObjectBox>(
    _entities[0].properties[2],
  );

  /// See [BrandObjectBox.externalId].
  static final externalId = obx.QueryStringProperty<BrandObjectBox>(
    _entities[0].properties[3],
  );
}

/// [CategoryObjectBox] entity fields to define ObjectBox queries.
class CategoryObjectBox_ {
  /// See [CategoryObjectBox.id].
  static final id = obx.QueryIntegerProperty<CategoryObjectBox>(
    _entities[1].properties[0],
  );

  /// See [CategoryObjectBox.name].
  static final name = obx.QueryStringProperty<CategoryObjectBox>(
    _entities[1].properties[1],
  );

  /// See [CategoryObjectBox.url].
  static final url = obx.QueryStringProperty<CategoryObjectBox>(
    _entities[1].properties[2],
  );

  /// See [CategoryObjectBox.items].
  static final items = obx.QueryIntegerProperty<CategoryObjectBox>(
    _entities[1].properties[3],
  );

  /// See [CategoryObjectBox.externalId].
  static final externalId = obx.QueryStringProperty<CategoryObjectBox>(
    _entities[1].properties[4],
  );

  /// See [CategoryObjectBox.brands].
  static final brands = obx.QueryStringProperty<CategoryObjectBox>(
    _entities[1].properties[5],
  );
}

/// [MediaObjectBox] entity fields to define ObjectBox queries.
class MediaObjectBox_ {
  /// See [MediaObjectBox.id].
  static final id = obx.QueryIntegerProperty<MediaObjectBox>(
    _entities[2].properties[0],
  );

  /// See [MediaObjectBox.url].
  static final url = obx.QueryStringProperty<MediaObjectBox>(
    _entities[2].properties[1],
  );

  /// See [MediaObjectBox.type].
  static final type = obx.QueryStringProperty<MediaObjectBox>(
    _entities[2].properties[2],
  );

  /// See [MediaObjectBox.productId].
  static final productId = obx.QueryIntegerProperty<MediaObjectBox>(
    _entities[2].properties[3],
  );
}

/// [ProductObjectBox] entity fields to define ObjectBox queries.
class ProductObjectBox_ {
  /// See [ProductObjectBox.id].
  static final id = obx.QueryIntegerProperty<ProductObjectBox>(
    _entities[3].properties[0],
  );

  /// See [ProductObjectBox.name].
  static final name = obx.QueryStringProperty<ProductObjectBox>(
    _entities[3].properties[1],
  );

  /// See [ProductObjectBox.slug].
  static final slug = obx.QueryStringProperty<ProductObjectBox>(
    _entities[3].properties[2],
  );

  /// See [ProductObjectBox.warranty].
  static final warranty = obx.QueryStringProperty<ProductObjectBox>(
    _entities[3].properties[3],
  );

  /// See [ProductObjectBox.state].
  static final state = obx.QueryStringProperty<ProductObjectBox>(
    _entities[3].properties[4],
  );

  /// See [ProductObjectBox.description].
  static final description = obx.QueryStringProperty<ProductObjectBox>(
    _entities[3].properties[5],
  );

  /// See [ProductObjectBox.price].
  static final price = obx.QueryDoubleProperty<ProductObjectBox>(
    _entities[3].properties[6],
  );

  /// See [ProductObjectBox.discount].
  static final discount = obx.QueryDoubleProperty<ProductObjectBox>(
    _entities[3].properties[7],
  );

  /// See [ProductObjectBox.featuresJson].
  static final featuresJson = obx.QueryStringProperty<ProductObjectBox>(
    _entities[3].properties[8],
  );

  /// See [ProductObjectBox.medias].
  static final medias = obx.QueryStringProperty<ProductObjectBox>(
    _entities[3].properties[9],
  );

  /// See [ProductObjectBox.categoryId].
  static final categoryId = obx.QueryStringProperty<ProductObjectBox>(
    _entities[3].properties[10],
  );

  /// See [ProductObjectBox.brandId].
  static final brandId = obx.QueryStringProperty<ProductObjectBox>(
    _entities[3].properties[11],
  );

  /// See [ProductObjectBox.externalId].
  static final externalId = obx.QueryIntegerProperty<ProductObjectBox>(
    _entities[3].properties[12],
  );

  /// See [ProductObjectBox.category].
  static final category = obx.QueryStringProperty<ProductObjectBox>(
    _entities[3].properties[13],
  );

  /// See [ProductObjectBox.brand].
  static final brand = obx.QueryStringProperty<ProductObjectBox>(
    _entities[3].properties[14],
  );

  /// See [ProductObjectBox.cta].
  static final cta = obx.QueryStringProperty<ProductObjectBox>(
    _entities[3].properties[15],
  );
}

/// [BannerObjectBox] entity fields to define ObjectBox queries.
class BannerObjectBox_ {
  /// See [BannerObjectBox.id].
  static final id = obx.QueryIntegerProperty<BannerObjectBox>(
    _entities[4].properties[0],
  );

  /// See [BannerObjectBox.externalId].
  static final externalId = obx.QueryIntegerProperty<BannerObjectBox>(
    _entities[4].properties[1],
  );

  /// See [BannerObjectBox.title].
  static final title = obx.QueryStringProperty<BannerObjectBox>(
    _entities[4].properties[2],
  );

  /// See [BannerObjectBox.description].
  static final description = obx.QueryStringProperty<BannerObjectBox>(
    _entities[4].properties[3],
  );

  /// See [BannerObjectBox.image].
  static final image = obx.QueryStringProperty<BannerObjectBox>(
    _entities[4].properties[4],
  );

  /// See [BannerObjectBox.link].
  static final link = obx.QueryStringProperty<BannerObjectBox>(
    _entities[4].properties[5],
  );
}

/// [ChatObjectBox] entity fields to define ObjectBox queries.
class ChatObjectBox_ {
  /// See [ChatObjectBox.id].
  static final id = obx.QueryIntegerProperty<ChatObjectBox>(
    _entities[5].properties[0],
  );

  /// See [ChatObjectBox.text].
  static final text = obx.QueryStringProperty<ChatObjectBox>(
    _entities[5].properties[1],
  );

  /// See [ChatObjectBox.isUser].
  static final isUser = obx.QueryBooleanProperty<ChatObjectBox>(
    _entities[5].properties[2],
  );

  /// See [ChatObjectBox.timestamp].
  static final timestamp = obx.QueryStringProperty<ChatObjectBox>(
    _entities[5].properties[3],
  );

  /// See [ChatObjectBox.externalId].
  static final externalId = obx.QueryStringProperty<ChatObjectBox>(
    _entities[5].properties[4],
  );
}

/// [NotificationObjectBox] entity fields to define ObjectBox queries.
class NotificationObjectBox_ {
  /// See [NotificationObjectBox.id].
  static final id = obx.QueryIntegerProperty<NotificationObjectBox>(
    _entities[6].properties[0],
  );

  /// See [NotificationObjectBox.title].
  static final title = obx.QueryStringProperty<NotificationObjectBox>(
    _entities[6].properties[1],
  );

  /// See [NotificationObjectBox.body].
  static final body = obx.QueryStringProperty<NotificationObjectBox>(
    _entities[6].properties[2],
  );

  /// See [NotificationObjectBox.type].
  static final type = obx.QueryStringProperty<NotificationObjectBox>(
    _entities[6].properties[3],
  );

  /// See [NotificationObjectBox.data].
  static final data = obx.QueryStringProperty<NotificationObjectBox>(
    _entities[6].properties[4],
  );

  /// See [NotificationObjectBox.receivedAt].
  static final receivedAt = obx.QueryDateProperty<NotificationObjectBox>(
    _entities[6].properties[5],
  );

  /// See [NotificationObjectBox.isRead].
  static final isRead = obx.QueryBooleanProperty<NotificationObjectBox>(
    _entities[6].properties[6],
  );
}
